### ISSUE TITLE
nginx伪静态错误，宝塔

### ISSUE THREAD

**Issue by wintsa123** [lichenzero/kms_server_webui#1]
nginx: [emerg] invalid condition "%" in /www/server/panel/vhost/rewrite/kms.wintsa.cn.conf:4
nginx: configuration file /www/server/nginx/conf/nginx.conf test failed
how to do.

**Comment by D3CODING** [comment]
本程序测试环境为Apache，Nginx规则为在线转换生成，未测试稳定性，请尝试使用以下规则代替：

```
location / {
  if (!-e $request_filename){
    rewrite ^(.+)$ /$1.php break;
  }
}
```
如仍未正常，请尝试修改HTML文件为如下内容

1. 第46行

```
<p>4、如果激活失败可先<a href="./clean.php">下载清除脚本</a>并运行后再次尝试激活。</p>
```

2. 第50行

```
<form action="./kms.php" method="post" role="form">
```

修改后不需要设置伪静态即可运行，但是无法隐藏网址中的php后缀。
