### ISSUE TITLE
nginx 405

### ISSUE THREAD

**Issue by ldxw** [lichenzero/kms_server_webui#2]
伪静态
405 Not Allowed

**Comment by D3CODING** [comment]
nginx不允许从html文件发出POST请求，将文件`index.html`改名为`index.php`即可。

**Comment by ldxw** [comment]
> nginx不允许从html文件发出POST请求，将文件`index.html`改名为`index.php`即可。

伪静态后下载的文件没后缀咋回事啊。。伪静态问题？nginx的

**Comment by D3CODING** [comment]
文件名是通过设置请求响应头实现的，如果浏览器调用第三方下载器，可能会因为无法接收前端传递的POST参数导致下载脚本失败，可以尝试禁用第三方下载工具或将前端和后端改为GET请求。

**Comment by D3CODING** [comment]
如果伪静态存在问题，可以尝试去掉伪静态，将前端index.html中的
`<form action="./kms" method="post" role="form">`
改为
`<form action="./kms.php" method="post" role="form">`
因为设置伪静态仅仅为了隐藏PHP后缀
